### ISSUE TITLE
User Story 1.1: Uploading pictures (4 story points)

### ISSUE THREAD

**Issue by TZnoj** [AbdulSir/InstaPIc#14]
As a user I would like to be able to post my pictures to InstaPic so that they are available.

**Comment by TZnoj** [comment]
Acceptance Test:
A user signs into the website and logs into their account.
They click on the upload picture button and are prompted to choose a photo.
Once they have selected their photo, they can click the accept button if they want to upload the chosen photo.
The system then accepts the photo and uploads the photo to the database.
Once uploaded, users should be able to see the photo on the user's profile and in their feed.

**Comment by AbdulSir** [comment]
> Acceptance Test:
> A user signs into the website and logs into their account.
> They click on the upload picture button and are prompted to choose a photo.
> Once they have selected their photo, they can click the accept button if they want to upload the chosen photo.
> The system then accepts the photo and uploads the photo to the database.
> Once uploaded, users should be able to see the photo on the user's profile and in their feed.

This acceptance test was checked and the user story works successfully. Users are prompted to share their photo with the people that follow them on the feed page. An upload button was created and it allows the user to choose a photo from their device and do basic edits if necessary on the photo and upload it to the feed page.
