### ISSUE TITLE
User Story 1.2: Viewing pictures that User uploaded as well as those uploaded by those he follows  (4 story points)

### ISSUE THREAD

**Issue by TZnoj** [AbdulSir/InstaPIc#15]
As a user I would like to be able to see photos of people I follow so I can know what the other users are doing as well as my own.

**Comment by TZnoj** [comment]
Acceptance Test:
A user signs into the website and logs into their account.
The user can change the page to their feed.
Once on their feed they should see their photos and the photos of the users they follow.
The user can follow another user and then see that user's photos on the feed.

**Comment by AbdulSir** [comment]
> Acceptance Test:
> A user signs into the website and logs into their account.
> The user can change the page to their feed.
> Once on their feed they should see their photos and the photos of the users they follow.
> The user can follow another user and then see that user's photos on the feed.

This acceptance test work. A user can log into his/her account and see photos on the feed page. those photos were either uploaded by the user or they belong to other users that are followed by the user.
