### ISSUE TITLE
User story 2.1: Following another user (4 story points)

### ISSUE THREAD

**Issue by AbdulSir** [AbdulSir/InstaPIc#24]

**Comment by TZnoj** [comment]
Acceptance Test:
A user signs into the website and logs into their account.
The user searches for a user in the search bar.
If the user exists, then they are redirected to their page.
They can then press the follow button and they will be following that user.

**Comment by AbdulSir** [comment]
> Acceptance Test:
> A user signs into the website and logs into their account.
> The user searches for a user in the search bar.
> If the user exists, then they are redirected to their page.
> They can then press the follow button and they will be following that user.

The acceptance test is verified successfully. Any user can search for existing users in the url. if they are found, the website will direct you to their profile page and a follow button was placed there to give other users the option to follow this specific user. Once a user is followed, that user's posts are shown in the feed page of whoever clicked follow on this user.
