### ISSUE TITLE
User story 2.2: Searching for users to follow (6 story points)

### ISSUE THREAD

**Issue by AbdulSir** [AbdulSir/InstaPIc#26]

**Comment by TZnoj** [comment]
Acceptance Test:
A user signs into the website and logs into their account.
They can then click on the search bar and type in a name.
If a user by that name exists, then the user will be redirected to that page.

**Comment by AbdulSir** [comment]
> Acceptance Test:
> A user signs into the website and logs into their account.
> They can then click on the search bar and type in a name.
> If a user by that name exists, then the user will be redirected to that page.

For this user story, users can only search for other users in the url. and if they exist in the database they system will direct the user to the profile of the searched user.
