### ISSUE TITLE
User story 3.1: Posting a comment on a picture (4 story points)

### ISSUE THREAD

**Issue by AbdulSir** [AbdulSir/InstaPIc#28]

**Comment by TZnoj** [comment]
Acceptance Test:
A user signs into the website and logs into their account.
On their feed or on their profile, they can see photos.
Each photo will have a comment section.
Each comment will be displayed in that section with who wrote the comment.
The user can write a comment in the text box and hit submit.
The comment will then be added to the existing list of comments with their name attached.

**Comment by AbdulSir** [comment]
> Acceptance Test:
> A user signs into the website and logs into their account.
> On their feed or on their profile, they can see photos.
> Each photo will have a comment section.
> Each comment will be displayed in that section with who wrote the comment.
> The user can write a comment in the text box and hit submit.
> The comment will then be added to the existing list of comments with their name attached.

This acceptance test was verified successfully. Each photo has a comment section and every written comment is attached below the photo, along with the name of person who commented. The user can reply to those comments by writing in the text area inside the comments section.
