### ISSUE TITLE
User story 4.1: A like option for every posted picture (5 story points)

### ISSUE THREAD

**Issue by AbdulSir** [AbdulSir/InstaPIc#34]

**Comment by TZnoj** [comment]
Acceptance Test:
A user signs into the website and logs into their account.
On their profile or on their feed the user will see photos posted by them or other users.
The photos will have a "like" button.
The user will be able to press the button and the photo that will be marked as liked.

**Comment by AbdulSir** [comment]
The acceptance test works. Any photo that is posted on the feed page has a like button which allows other users to like the posted photo.
