### ISSUE TITLE
User story 5.1: Displaying the newly posted pictures on top of the page (5 story points)

### ISSUE THREAD

**Issue by AbdulSir** [AbdulSir/InstaPIc#35]

**Comment by TZnoj** [comment]
Acceptance Test:
A user signs into the website and logs into their account.
The user can either go to their feed or their profile to view photos.
The user will see newer content at the top of the page with the oldest content being at the bottom.

**Comment by AbdulSir** [comment]
> Acceptance Test:
> A user signs into the website and logs into their account.
> The user can either go to their feed or their profile to view photos.
> The user will see newer content at the top of the page with the oldest content being at the bottom.

This test was passed. Any user that logs into their account will be directed to their feed page where they see the newly posted pictures first then the oldest. This was verified by comparing the time of upload of each picture.
